MTSD_FULLY_ANNOTATED_IMAGES_TRAIN="mtsd_fully_annotated_images_train"
MTSD_FULLY_ANNOTATED_IMAGES_VAL="mtsd_fully_annotated_images_val"
MTSD_FULLY_ANNOTATED_IMAGES_TRAIN_CROPPED="mtsd_fully_annotated_images_train_cropped"
MTSD_FULLY_ANNOTATED_IMAGES_VAL_CROPPED="mtsd_fully_annotated_images_val_cropped"