import logger

dataset_dir = "../data"
dataset_dir_annotations = dataset_dir + "/annotations"
dataset_dir_annotations_generated = dataset_dir_annotations + "/generated"
dataset_dir_annotations_original = dataset_dir_annotations + "/original"
dataset_dir_images = dataset_dir + "/images"
dataset_dir_splits = dataset_dir + "/splits"
dataset_file_extension_annotations = ".json"
dataset_file_extension_images = ".jpg"

filter_file_name = "filter.txt"
filter_print_params = True
filter_frame_ispano = True
filter_object_keys = []
filter_object_labels = []
filter_object_properties = 0
filter_object_barrier = 0
filter_object_occluded = 0
filter_object_out_of_frame = 0
filter_object_exterior = 0
filter_object_ambiguous = 0
filter_object_included = 0
filter_object_direction_or_information = 0
filter_object_highway = 0
filter_object_dummy = 0

generate_dataset_color = {
    "complementary--accident-area--g3": "color--white",
    "complementary--both-directions--g1": "color--yellow",
    "complementary--buses--g1": "color--white",
    "complementary--chevron-left--g1": "color--yellow",
    "complementary--chevron-left--g2": "color--blue",
    "complementary--chevron-left--g3": "color--black",
    "complementary--chevron-left--g4": "color--blue",
    "complementary--chevron-left--g5": "color--white",
    "complementary--chevron-right--g1": "color--yellow",
    "complementary--chevron-right--g3": "color--white",
    "complementary--chevron-right--g4": "color--blue",
    "complementary--chevron-right--g5": "color--white",
    "complementary--chevron-right-unsure--g6": "color--blue",
    "complementary--distance--g1": "color--white",
    "complementary--distance--g2": "color--white",
    "complementary--distance--g3": "color--yellow",
    "complementary--except-bicycles--g1": "color--white",
    "complementary--extent-of-prohibition-area-both-direction--g1": "color--white",
    "complementary--go-left--g1": "color--white",
    "complementary--go-right--g1": "color--white",
    "complementary--go-right--g2": "color--white",
    "complementary--keep-left--g1": "color--yellow",
    "complementary--keep-right--g1": "color--yellow",
    "complementary--maximum-speed-limit-15--g1": "color--yellow",
    "complementary--maximum-speed-limit-20--g1": "color--yellow",
    "complementary--maximum-speed-limit-25--g1": "color--yellow",
    "complementary--maximum-speed-limit-30--g1": "color--yellow",
    "complementary--maximum-speed-limit-35--g1": "color--yellow",
    "complementary--maximum-speed-limit-40--g1": "color--yellow",
    "complementary--maximum-speed-limit-45--g1": "color--yellow",
    "complementary--maximum-speed-limit-50--g1": "color--yellow",
    "complementary--maximum-speed-limit-55--g1": "color--yellow",
    "complementary--maximum-speed-limit-70--g1": "color--yellow",
    "complementary--maximum-speed-limit-75--g1": "color--yellow",
    "complementary--obstacle-delineator--g1": "color--yellow",
    "complementary--obstacle-delineator--g2": "color--yellow",
    "complementary--one-direction-left--g1": "color--yellow",
    "complementary--one-direction-right--g1": "color--yellow",
    "complementary--pass-right--g1": "color--white",
    "complementary--priority-route-at-intersection--g1": "color--white",
    "complementary--tow-away-zone--g1": "color--white",
    "complementary--trucks--g1": "color--white",
    "complementary--trucks-turn-right--g1": "color--yellow",
    "complementary--turn-left--g2": "color--white",
    "complementary--turn-right--g2": "color--white",
    "information--airport--g1": "color--blue",
    "information--airport--g2": "color--green",
    "information--bike-route--g1": "color--green",
    "information--bus-stop--g1": "color--yellow",
    "information--camp--g1": "color--blue",
    "information--central-lane--g1": "color--blue",
    "information--children--g1": "color--blue",
    "information--dead-end--g1": "color--blue",
    "information--dead-end-except-bicycles--g1": "color--blue",
    "information--disabled-persons--g1": "color--blue",
    "information--emergency-facility--g2": "color--white",
    "information--end-of-built-up-area--g1": "color--white",
    "information--end-of-limited-access-road--g1": "color--blue",
    "information--end-of-living-street--g1": "color--blue",
    "information--end-of-motorway--g1": "color--blue",
    "information--end-of-pedestrians-only--g2": "color--blue",
    "information--food--g2": "color--white",
    "information--gas-station--g1": "color--blue",
    "information--gas-station--g3": "color--blue",
    "information--highway-exit--g1": "color--green",
    "information--highway-interstate-route--g2": "color--green",
    "information--hospital--g1": "color--blue",
    "information--interstate-route--g1": "color--blue",
    "information--limited-access-road--g1": "color--blue",
    "information--living-street--g1": "color--blue",
    "information--lodging--g1": "color--blue",
    "information--minimum-speed-40--g1": "color--blue",
    "information--motorway--g1": "color--blue",
    "information--no-parking--g3": "color--blue",
    "information--parking--g1": "color--blue",
    "information--parking--g2": "color--blue",
    "information--parking--g3": "color--white",
    "information--parking--g45": "color--blue",
    "information--parking--g5": "color--white",
    "information--parking--g6": "color--blue",
    "information--pedestrians-crossing--g1": "color--blue",
    "information--pedestrians-crossing--g2": "color--blue",
    "information--road-bump--g1": "color--blue",
    "information--safety-area--g2": "color--blue",
    "information--stairs--g1": "color--blue",
    "information--telephone--g1": "color--blue",
    "information--telephone--g2": "color--white",
    "information--trailer-camping--g1": "color--blue",
    "information--tram-bus-stop--g2": "color--blue",
    "other-sign": "color--undefine",
    "regulatory--bicycles-only--g1": "color--blue",
    "regulatory--bicycles-only--g2": "color--white",
    "regulatory--bicycles-only--g3": "color--black",
    "regulatory--buses-only--g1": "color--blue",
    "regulatory--detour-left--g1": "color--white",
    "regulatory--do-not-block-intersection--g1": "color--white",
    "regulatory--do-not-stop-on-tracks--g1": "color--white",
    "regulatory--dual-lanes-go-straight-on-left--g1": "color--white",
    "regulatory--dual-lanes-go-straight-on-right--g1": "color--white",
    "regulatory--dual-lanes-turn-left-no-u-turn--g1": "color--white",
    "regulatory--dual-lanes-turn-left-or-straight--g1": "color--white",
    "regulatory--dual-lanes-turn-right-or-straight--g1": "color--white",
    "regulatory--dual-path-bicycles-and-pedestrians--g1": "color--blue",
    "regulatory--dual-path-pedestrians-and-bicycles--g1": "color--blue",
    "regulatory--end-of-bicycles-only--g1": "color--blue",
    "regulatory--end-of-buses-only--g1": "color--blue",
    "regulatory--end-of-maximum-speed-limit-30--g2": "color--white",
    "regulatory--end-of-maximum-speed-limit-70--g1": "color--white",
    "regulatory--end-of-maximum-speed-limit-70--g2": "color--white",
    "regulatory--end-of-no-parking--g1": "color--white",
    "regulatory--end-of-priority-road--g1": "color--yellow",
    "regulatory--end-of-prohibition--g1": "color--white",
    "regulatory--end-of-speed-limit-zone--g1": "color--white",
    "regulatory--give-way-to-oncoming-traffic--g1": "color--white",
    "regulatory--go-straight--g1": "color--blue",
    "regulatory--go-straight--g3": "color--white",
    "regulatory--go-straight-or-turn-left--g1": "color--blue",
    "regulatory--go-straight-or-turn-left--g2": "color--white",
    "regulatory--go-straight-or-turn-left--g3": "color--white",
    "regulatory--go-straight-or-turn-right--g1": "color--blue",
    "regulatory--go-straight-or-turn-right--g3": "color--white",
    "regulatory--height-limit--g1": "color--white",
    "regulatory--keep-left--g1": "color--blue",
    "regulatory--keep-left--g2": "color--white",
    "regulatory--keep-right--g1": "color--blue",
    "regulatory--keep-right--g2": "color--white/yellow",
    "regulatory--keep-right--g4": "color--white",
    "regulatory--keep-right--g6": "color--white",
    "regulatory--lane-control--g1": "color--white",
    "regulatory--left-turn-yield-on-green--g1": "color--white",
    "regulatory--maximum-speed-limit-10--g1": "color--white",
    "regulatory--maximum-speed-limit-100--g1": "color--white",
    "regulatory--maximum-speed-limit-100--g3": "color--white",
    "regulatory--maximum-speed-limit-110--g1": "color--white",
    "regulatory--maximum-speed-limit-120--g1": "color--white",
    "regulatory--maximum-speed-limit-15--g1": "color--white",
    "regulatory--maximum-speed-limit-20--g1": "color--white",
    "regulatory--maximum-speed-limit-25--g1": "color--white",
    "regulatory--maximum-speed-limit-25--g2": "color--white",
    "regulatory--maximum-speed-limit-30--g1": "color--white",
    "regulatory--maximum-speed-limit-30--g3": "color--white",
    "regulatory--maximum-speed-limit-35--g2": "color--white",
    "regulatory--maximum-speed-limit-40--g1": "color--white",
    "regulatory--maximum-speed-limit-40--g3": "color--white",
    "regulatory--maximum-speed-limit-40--g6": "color--white",
    "regulatory--maximum-speed-limit-45--g1": "color--white",
    "regulatory--maximum-speed-limit-45--g3": "color--white",
    "regulatory--maximum-speed-limit-5--g1": "color--white",
    "regulatory--maximum-speed-limit-50--g1": "color--white",
    "regulatory--maximum-speed-limit-50--g6": "color--white",
    "regulatory--maximum-speed-limit-55--g2": "color--white",
    "regulatory--maximum-speed-limit-60--g1": "color--white",
    "regulatory--maximum-speed-limit-65--g2": "color--white",
    "regulatory--maximum-speed-limit-70--g1": "color--white",
    "regulatory--maximum-speed-limit-80--g1": "color--white",
    "regulatory--maximum-speed-limit-90--g1": "color--white",
    "regulatory--maximum-speed-limit-led-100--g1": "color--black",
    "regulatory--maximum-speed-limit-led-60--g1": "color--black",
    "regulatory--maximum-speed-limit-led-80--g1": "color--black",
    "regulatory--minimum-safe-distance--g1": "color--white",
    "regulatory--mopeds-and-bicycles-only--g1": "color--blue",
    "regulatory--no-bicycles--g1": "color--white",
    "regulatory--no-bicycles--g2": "color--white",
    "regulatory--no-bicycles--g3": "color--white",
    "regulatory--no-buses--g3": "color--white",
    "regulatory--no-entry--g1": "color--red",
    "regulatory--no-hawkers--g1": "color--white",
    "regulatory--no-heavy-goods-vehicles--g1": "color--white",
    "regulatory--no-heavy-goods-vehicles--g2": "color--white",
    "regulatory--no-heavy-goods-vehicles--g4": "color--white",
    "regulatory--no-heavy-goods-vehicles--g5": "color--white",
    "regulatory--no-heavy-goods-vehicles-or-buses--g1": "color--white",
    "regulatory--no-left-turn--g1": "color--white/yellow",
    "regulatory--no-left-turn--g2": "color--white",
    "regulatory--no-left-turn--g3": "color--white",
    "regulatory--no-mopeds-or-bicycles--g1": "color--white",
    "regulatory--no-motor-vehicle-trailers--g1": "color--white",
    "regulatory--no-motor-vehicles--g1": "color--white",
    "regulatory--no-motor-vehicles--g4": "color--white",
    "regulatory--no-motor-vehicles-except-motorcycles--g1": "color--white",
    "regulatory--no-motor-vehicles-except-motorcycles--g2": "color--white",
    "regulatory--no-motorcycles--g1": "color--white",
    "regulatory--no-motorcycles--g2": "color--white",
    "regulatory--no-overtaking--g1": "color--white",
    "regulatory--no-overtaking--g2": "color--white",
    "regulatory--no-overtaking--g4": "color--white",
    "regulatory--no-overtaking--g5": "color--white",
    "regulatory--no-overtaking-by-heavy-goods-vehicles--g1": "color--white",
    "regulatory--no-parking--g1": "color--blue",
    "regulatory--no-parking--g2": "color--white",
    "regulatory--no-parking--g5": "color--white",
    "regulatory--no-parking-or-no-stopping--g1": "color--white",
    "regulatory--no-parking-or-no-stopping--g2": "color--white",
    "regulatory--no-parking-or-no-stopping--g3": "color--white",
    "regulatory--no-pedestrians--g1": "color--white",
    "regulatory--no-pedestrians--g2": "color--white",
    "regulatory--no-pedestrians--g3": "color--white",
    "regulatory--no-pedestrians-or-bicycles--g1": "color--white",
    "regulatory--no-right-turn--g1": "color--white",
    "regulatory--no-right-turn--g2": "color--white",
    "regulatory--no-right-turn--g3": "color--white",
    "regulatory--no-stopping--g15": "color--blue",
    "regulatory--no-stopping--g2": "color--white",
    "regulatory--no-stopping--g4": "color--white",
    "regulatory--no-stopping--g5": "color--whtie",
    "regulatory--no-stopping--g8": "color--blue",
    "regulatory--no-straight-through--g1": "color--white",
    "regulatory--no-straight-through--g2": "color--white",
    "regulatory--no-turn-on-red--g1": "color--white",
    "regulatory--no-turn-on-red--g2": "color--white",
    "regulatory--no-turn-on-red--g3": "color--white",
    "regulatory--no-turns--g1": "color--white",
    "regulatory--no-u-turn--g1": "color--white",
    "regulatory--no-u-turn--g2": "color--white",
    "regulatory--no-u-turn--g3": "color--white",
    "regulatory--no-vehicles-carrying-dangerous-goods--g1": "color--white",
    "regulatory--one-way-left--g1": "color--blue",
    "regulatory--one-way-left--g2": "color--white",
    "regulatory--one-way-left--g3": "color--black",
    "regulatory--one-way-right--g1": "color--blue",
    "regulatory--one-way-right--g2": "color--white",
    "regulatory--one-way-right--g3": "color--black",
    "regulatory--one-way-straight--g1": "color--blue",
    "regulatory--parking-restrictions--g2": "color--white",
    "regulatory--pass-on-either-side--g1": "color--blue",
    "regulatory--pass-on-either-side--g2": "color--blue",
    "regulatory--passing-lane-ahead--g1": "color--white",
    "regulatory--pedestrians-only--g1": "color--blue",
    "regulatory--pedestrians-only--g2": "color--blue",
    "regulatory--priority-over-oncoming-vehicles--g1": "color--blue",
    "regulatory--priority-road--g4": "color--yellow",
    "regulatory--radar-enforced--g1": "color--white",
    "regulatory--reversible-lanes--g2": "color--white",
    "regulatory--road-closed--g1": "color--white",
    "regulatory--road-closed--g2": "color--white",
    "regulatory--road-closed-to-vehicles--g1": "color--white",
    "regulatory--road-closed-to-vehicles--g3": "color--white",
    "regulatory--roundabout--g1": "color--blue",
    "regulatory--roundabout--g2": "color--white",
    "regulatory--shared-path-bicycles-and-pedestrians--g1": "color--blue",
    "regulatory--shared-path-pedestrians-and-bicycles--g1": "color--blue",
    "regulatory--stop--g1": "color--red",
    "regulatory--stop--g10": "color--red",
    "regulatory--stop--g2": "color--red",
    "regulatory--stop-here-on-red-or-flashing-light--g1": "color--white",
    "regulatory--stop-here-on-red-or-flashing-light--g2": "color--white",
    "regulatory--stop-signals--g1": "color--white?",
    "regulatory--text-four-lines--g1": "color--white",
    "regulatory--triple-lanes-turn-left-center-lane--g1": "color--white",
    "regulatory--truck-speed-limit-60--g1": "color--white",
    "regulatory--turn-left--g1": "color--blue",
    "regulatory--turn-left--g2": "color--white",
    "regulatory--turn-left--g3": "color--white",
    "regulatory--turn-left-ahead--g1": "color--blue",
    "regulatory--turn-right--g1": "color--blue",
    "regulatory--turn-right--g2": "color--white",
    "regulatory--turn-right--g3": "color--white",
    "regulatory--turn-right-ahead--g1": "color--blue",
    "regulatory--turn-right-ahead--g2": "color--white",
    "regulatory--turning-vehicles-yield-to-pedestrians--g1": "color--yellow?white?",
    "regulatory--u-turn--g1": "color--blue",
    "regulatory--weight-limit--g1": "color--white",
    "regulatory--weight-limit-with-trucks--g1": "color--white",
    "regulatory--width-limit--g1": "color--white",
    "regulatory--wrong-way--g1": "color--red",
    "regulatory--yield--g1": "color--white",
    "warning--accidental-area-unsure--g2": "color--yellow",
    "warning--added-lane-right--g1": "color--yellow",
    "warning--bicycles-crossing--g1": "color--white",
    "warning--bicycles-crossing--g2": "color--yellow",
    "warning--bicycles-crossing--g3": "color--yellow",
    "warning--bus-stop-ahead--g3": "color--yellow",
    "warning--children--g1": "color--white",
    "warning--children--g2": "color--yellow",
    "warning--crossroads--g1": "color--white",
    "warning--crossroads--g3": "color--yellow",
    "warning--crossroads-with-priority-to-the-right--g1": "color--white",
    "warning--curve-left--g1": "color--white",
    "warning--curve-left--g2": "color--yellow",
    "warning--curve-right--g1": "color--white",
    "warning--curve-right--g2": "color--yellow",
    "warning--dip--g2": "color--yellow",
    "warning--divided-highway-ends--g1": "color--yellow",
    "warning--divided-highway-ends--g2": "color--yellow",
    "warning--domestic-animals--g1": "color--white",
    "warning--domestic-animals--g3": "color--yellow",
    "warning--double-curve-first-left--g1": "color--white",
    "warning--double-curve-first-left--g2": "color--yellow",
    "warning--double-curve-first-right--g1": "color--white",
    "warning--double-curve-first-right--g2": "color--yellow",
    "warning--double-reverse-curve-right--g1": "color--orange?",
    "warning--double-turn-first-right--g1": "color--yellow",
    "warning--dual-lanes-right-turn-or-go-straight--g1": "color--yellow",
    "warning--emergency-vehicles--g1": "color--yellow",
    "warning--equestrians-crossing--g2": "color--yellow",
    "warning--falling-rocks-or-debris-right--g1": "color--white/black",
    "warning--falling-rocks-or-debris-right--g2": "color--yellow",
    "warning--falling-rocks-or-debris-right--g4": "color--yellow",
    "warning--flaggers-in-road--g1": "color--orange?",
    "warning--hairpin-curve-left--g1": "color--yellow",
    "warning--hairpin-curve-left--g3": "color--white",
    "warning--hairpin-curve-right--g1": "color--yellow",
    "warning--hairpin-curve-right--g4": "color--yellow",
    "warning--height-restriction--g2": "color--yellow",
    "warning--horizontal-alignment-left--g1": "color--yellow",
    "warning--horizontal-alignment-right--g1": "color--yellow",
    "warning--horizontal-alignment-right--g3": "color--yellow",
    "warning--junction-with-a-side-road-acute-left--g1": "color--yellow",
    "warning--junction-with-a-side-road-acute-right--g1": "color--yellow",
    "warning--junction-with-a-side-road-perpendicular-left--g1": "color--white",
    "warning--junction-with-a-side-road-perpendicular-left--g3": "color--yellow",
    "warning--junction-with-a-side-road-perpendicular-left--g4": "color--yellow/orange",
    "warning--junction-with-a-side-road-perpendicular-right--g1": "color--white",
    "warning--junction-with-a-side-road-perpendicular-right--g3": "color--yellow",
    "warning--kangaloo-crossing--g1": "color--yellow",
    "warning--loop-270-degree--g1": "color--yellow",
    "warning--narrow-bridge--g1": "color--yellow",
    "warning--narrow-bridge--g3": "color--white",
    "warning--offset-roads--g3": "color--yellow",
    "warning--other-danger--g1": "color--white",
    "warning--other-danger--g3": "color--yellow",
    "warning--pass-left-or-right--g1": "color--yellow",
    "warning--pass-left-or-right--g2": "color--yellow",
    "warning--pedestrian-stumble-train--g1": "color--yellow",
    "warning--pedestrians-crossing--g1": "color--yellow",
    "warning--pedestrians-crossing--g10": "color--yellow",
    "warning--pedestrians-crossing--g11": "color--yellow",
    "warning--pedestrians-crossing--g12": "color--yellow",
    "warning--pedestrians-crossing--g4": "color--yellow",
    "warning--pedestrians-crossing--g5": "color--white/yellow",
    "warning--pedestrians-crossing--g9": "color--yellow",
    "warning--playground--g1": "color--yellow",
    "warning--playground--g3": "color--yellow",
    "warning--railroad-crossing--g1": "color--yellow",
    "warning--railroad-crossing--g3": "color--yellow",
    "warning--railroad-crossing--g4": "color--white?",
    "warning--railroad-crossing-with-barriers--g1": "color--white",
    "warning--railroad-crossing-with-barriers--g2": "color--yellow",
    "warning--railroad-crossing-with-barriers--g4": "color--yellow",
    "warning--railroad-crossing-without-barriers--g1": "color--white",
    "warning--railroad-crossing-without-barriers--g3": "color--white",
    "warning--railroad-crossing-without-barriers--g4": "color--yellow",
    "warning--railroad-intersection--g3": "color--yellow",
    "warning--railroad-intersection--g4": "color--yellow",
    "warning--restricted-zone--g1": "color--white",
    "warning--road-bump--g1": "color--white/yellow",
    "warning--road-bump--g2": "color--yellow",
    "warning--road-narrows--g1": "color--white",
    "warning--road-narrows--g2": "color--yellow",
    "warning--road-narrows-left--g1": "color--white",
    "warning--road-narrows-left--g2": "color--yellow",
    "warning--road-narrows-right--g1": "color--white",
    "warning--road-narrows-right--g2": "color--yellow",
    "warning--road-widens--g1": "color--yellow",
    "warning--road-widens-right--g1": "color--yellow",
    "warning--roadworks--g1": "color--white/yellow",
    "warning--roadworks--g2": "color--orange",
    "warning--roadworks--g3": "color--white/yellow",
    "warning--roadworks--g4": "color--orange",
    "warning--roadworks--g6": "color--black",
    "warning--roundabout--g1": "color--white",
    "warning--roundabout--g25": "color--yellow",
    "warning--school-zone--g2": "color--yellow",
    "warning--shared-lane-motorcycles-bicycles--g1": "color--yellow",
    "warning--slippery-motorcycles--g1": "color--yellow",
    "warning--slippery-road-surface--g1": "color--white/yellow",
    "warning--slippery-road-surface--g2": "color--yellow",
    "warning--steep-ascent--g7": "color--yellow",
    "warning--stop-ahead--g9": "color--yellow",
    "warning--t-roads--g1": "color--white",
    "warning--t-roads--g2": "color--yellow",
    "warning--texts--g1": "color--yellow",
    "warning--texts--g2": "color--yellow/orange",
    "warning--texts--g3": "color--yellow/orange",
    "warning--traffic-merges-left--g1": "color--yellow",
    "warning--traffic-merges-left--g2": "color--white",
    "warning--traffic-merges-right--g1": "color--yellow",
    "warning--traffic-merges-right--g2": "color--white/yellow",
    "warning--traffic-signals--g1": "color--white",
    "warning--traffic-signals--g2": "color--yellow",
    "warning--traffic-signals--g3": "color--yellow",
    "warning--traffic-signals--g4": "color--yellow",
    "warning--trail-crossing--g2": "color--yellow",
    "warning--trams-crossing--g1": "color--white",
    "warning--trucks-crossing--g1": "color--yellow",
    "warning--turn-left--g1": "color--yellow",
    "warning--turn-right--g1": "color--yellow",
    "warning--turn-right--g2": "color--yellow",
    "warning--two-way-traffic--g1": "color--white/yellow",
    "warning--two-way-traffic--g2": "color--yellow",
    "warning--uneven-road--g2": "color--yellow/orange",
    "warning--uneven-road--g6": "color--white",
    "warning--uneven-roads-ahead--g1": "color--yellow",
    "warning--wild-animals--g1": "color--white",
    "warning--wild-animals--g4": "color--yellow",
    "warning--winding-road-first-left--g1": "color--yellow",
    "warning--winding-road-first-left--g2": "color--white/yellow",
    "warning--winding-road-first-right--g1": "color--yellow",
    "warning--winding-road-first-right--g3": "color--white",
    "warning--wombat-crossing--g1": "color--yellow",
    "warning--y-roads--g1": "color--yellow",
}
generate_dataset_shape = {
    "name": "shape",
    "regulatory--one-way-left--g1": "shape--rectangle--wide",
    "regulatory--one-way-right--g1": "shape--rectangle--wide"
}
generate_dataset_symbol = {
    "name": "symbol",
    "regulatory--one-way-left--g1": "symbol--arrow--left",
    "regulatory--one-way-right--g1": "symbol--arrow--right"
}
generate_dataset_text = {
    "name": "text",
    "regulatory--stop--g1": "text--stop"
}
generate_datasets = [
    generate_dataset_color,
    generate_dataset_shape,
    generate_dataset_symbol,
    generate_dataset_text
]

label_file_name = "label.txt"

log_level = logger.LogLevel.trace

view_bounding_box_color = (0, 255, 0)
view_bounding_box_text_color = (0, 0, 0)
view_bounding_box_text_margin_x = 10
view_bounding_box_text_margin_y = 10
view_bounding_box_text_size = 1
view_bounding_box_thickness = 3
view_window_height = 900
